LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE_CLASS := STATIC_LIBRARIES
LOCAL_MODULE_SUFFIX := .a
LOCAL_UNINSTALLABLE_MODULE := true
LOCAL_MODULE := libmodemutils
LOCAL_SRC_FILES := liblgit_9x28.a
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/include
include $(BUILD_PREBUILT)


$(warning LOCAL_PATH = $(LOCAL_PATH))

